/*
 * Host tool: the boot-signing key and signed boot manifests for tepOS's
 * BootPolicyService (boot/include/tep/boot_manifest.h).
 *
 *   boot_sign keygen <private key file> <public key header>
 *       Make a new Ed25519 signing key (32-byte seed from /dev/urandom) and a
 *       C header with its public key, which tepOS is built with. Refuses to
 *       overwrite an existing private key.
 *
 *   boot_sign sign <private key file> <image> <name> <version> <manifest out>
 *       Write a signed manifest for <image>: its SHA-256, size, a short name
 *       and a version number (tepOS refuses versions below the highest it
 *       has accepted).
 *
 * The private key stays on the host: tepOS only ever holds the public key.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "monocypher-ed25519.h"
#include "sha256.h"
#include "tep/boot_manifest.h"

static void die(const char *msg)
{
    fprintf(stderr, "boot_sign: %s\n", msg);
    exit(1);
}

static void put32(uint8_t *p, uint32_t v)
{
    for (int i = 0; i < 4; i++) {
        p[i] = (uint8_t)(v >> (8 * i));
    }
}

static void put64(uint8_t *p, uint64_t v)
{
    for (int i = 0; i < 8; i++) {
        p[i] = (uint8_t)(v >> (8 * i));
    }
}

static void read_seed(const char *path, uint8_t seed[32])
{
    FILE *f = fopen(path, "rb");

    if (f == NULL || fread(seed, 1, 32, f) != 32) {
        die("cannot read the 32-byte private key");
    }
    fclose(f);
}

static int keygen(const char *key_path, const char *header_path)
{
    uint8_t seed[32], secret[64], public_key[32];
    FILE *r = fopen("/dev/urandom", "rb");

    if (access(key_path, F_OK) == 0) {
        die("private key already exists; not overwriting it");
    }
    if (r == NULL || fread(seed, 1, sizeof(seed), r) != sizeof(seed)) {
        die("cannot read /dev/urandom");
    }
    fclose(r);

    int fd = open(key_path, O_WRONLY | O_CREAT | O_EXCL, 0600);
    if (fd < 0 || write(fd, seed, sizeof(seed)) != (ssize_t)sizeof(seed) || close(fd) != 0) {
        die("cannot write the private key");
    }
    crypto_ed25519_key_pair(secret, public_key, seed);   /* wipes seed */
    crypto_wipe(secret, sizeof(secret));

    FILE *h = fopen(header_path, "w");
    if (h == NULL) {
        die("cannot write the public key header");
    }
    fprintf(h, "/* Generated by tools/boot_sign keygen: the public half of the host's boot-signing key. */\n");
    fprintf(h, "#define TEP_BOOT_PUBLIC_KEY {");
    for (int i = 0; i < 32; i++) {
        fprintf(h, "%s0x%02x", i ? ", " : " ", public_key[i]);
    }
    fprintf(h, " }\n");
    fclose(h);
    return 0;
}

static int sign(const char *key_path, const char *image_path, const char *name, const char *version,
                const char *out_path)
{
    uint8_t seed[32], secret[64], public_key[32];
    uint8_t manifest[TEP_BOOT_MANIFEST_SIZE] = { 0 };
    struct sha256_ctx ctx;
    uint8_t buf[65536];
    uint64_t size = 0;
    size_t n;
    FILE *f = fopen(image_path, "rb");

    if (f == NULL) {
        die("cannot open the image");
    }
    if (strlen(name) > TEP_BOOT_NAME_SIZE) {
        die("name longer than 16 bytes");
    }
    sha256_init(&ctx);
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0) {
        sha256_update(&ctx, buf, n);
        size += n;
    }
    fclose(f);

    memcpy(manifest, TEP_BOOT_MAGIC, 8);
    put32(manifest + 8, TEP_BOOT_FORMAT_VERSION);
    put32(manifest + 12, (uint32_t)strtoul(version, NULL, 10));
    put64(manifest + 16, size);
    memcpy(manifest + 24, name, strlen(name));
    sha256_final(&ctx, manifest + 40);

    read_seed(key_path, seed);
    crypto_ed25519_key_pair(secret, public_key, seed);
    crypto_ed25519_sign(manifest + TEP_BOOT_SIGNED_SIZE, secret, manifest, TEP_BOOT_SIGNED_SIZE);
    crypto_wipe(secret, sizeof(secret));

    FILE *o = fopen(out_path, "wb");
    if (o == NULL || fwrite(manifest, 1, sizeof(manifest), o) != sizeof(manifest) || fclose(o) != 0) {
        die("cannot write the manifest");
    }
    return 0;
}

int main(int argc, char **argv)
{
    if (argc == 4 && strcmp(argv[1], "keygen") == 0) {
        return keygen(argv[2], argv[3]);
    }
    if (argc == 7 && strcmp(argv[1], "sign") == 0) {
        return sign(argv[2], argv[3], argv[4], argv[5], argv[6]);
    }
    fprintf(stderr, "usage: boot_sign keygen <private key> <public key header>\n"
                    "       boot_sign sign <private key> <image> <name> <version> <manifest out>\n");
    return 2;
}
